version: '3.8'

services:
    db:
        image: mariadb:10.9.6
        restart: on-failure
        ports:
            - '127.0.0.1:3307:3306'
        networks:
            backend:
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: user
            MARIADB_PASSWORD: password
            MARIADB_DATABASE: database
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
            start_period: 5s
            interval: 5s

    backend:
        build:
            dockerfile: ./jar.Dockerfile
        ports:
            - '127.0.0.1:8080:8080'
        networks:
            backend:
        depends_on:
            - db
#        restart:
#            on-failure

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '127.0.0.1:8081:80'
        networks:
            - backend
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root

networks:
    backend:
